---
# Setup OCP4 Helper Node
- hosts: all
  handlers:
  - import_tasks: ../handlers/main.yaml
  remote_user: root


  tasks:
  - name: Install needed packages
    package:
      name:
        - "bind"
        - "bind-utils"
      state: present
  - name: Remove existing named config
    file:
      path: /etc/named.conf
      state: absent

  - name: Remove existing DNS zone files
    become: yes
    file:
      path: "/var/named/{{ item }}"
      state: absent
    with_items:
      - "zonefile.db"
      - "reverse.db"
  - name: Best effort SELinux repair - DNS
    shell: "restorecon -vR /var/named || true"

  - name: Write out named file
    become: yes
    template:
      src: ../templates/named.conf.j2
      dest: /etc/named.conf
    notify:
      - restart bind

  - name: Installing DNS Serialnumber generator
    become: yes
    copy:
      src: ../files/set-dns-serial.sh
      dest: /usr/local/bin/set-dns-serial.sh
      mode: '0555'

  - name: Set zone serial number
    shell: "/usr/local/bin/set-dns-serial.sh"
    register: dymanicserialnumber

  - name: Setting serial number as a fact
    set_fact:
      serialnumber: "{{ dymanicserialnumber.stdout }}"

  - name: Write out "{{ dns.domain | lower }}" zone file
    become: yes
    template:
      src: ../templates/zonefile.j2
      dest: /var/named/zonefile.db
      mode: '0644'
    notify:
      - restart bind

  - name: Write out reverse zone file
    become: yes
    template:
      src: ../templates/reverse.j2
      dest: /var/named/reverse.db
      mode: '0644'
    notify:
       - restart bind